### ISSUE TITLE
error: npm package deprecated

### ISSUE THREAD

**Issue by ramantalkin** [praxigento/mobi_app_generic_mage2#1]
│ │ └── punycode@1.4.1
  │ └── uuid@3.0.1
  ├─┬ request-progress@2.0.1
  │ └── throttleit@1.0.0
  └─┬ which@1.2.12
    └── isexe@1.1.2

npm ERR! Linux 4.4.0-62-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the phantomjs@2.1.7 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/mobi_app_generic_mage2/test/integration/npm-debug.log

Add file with timestamp mark into the web root...

Deployment is done. Launch post-installation script:
    sh ./bin/post_install.sh

i found this resource but unable to resolve 
there may be an update in npm packages which requires code update

**Comment by ramantalkin** [comment]
Install npm module for integration tests...
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated node-uuid@1.4.7: use uuid module instead

**Comment by flancer64** [comment]
Thanks for your attention.

This project is not completely ready. It will be redesigned and refactored (casperjs/phantomjs will be extracted into separate project at least). I cannot recommend you to use it now.

**Comment by flancer64** [comment]
Try [this sample](https://github.com/flancer32/sample_mage2_module) to get clean example of the Magento 2 app deployment used in MOBI project.
